# Generated by Django 4.1.2 on 2022-11-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=60)),
                ('created_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('P', 'Public'), ('F', 'Followers')], default='P', max_length=1)),
                ('is_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('user_id_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='twitter2.user')),
                ('user_id_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='twitter2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('content', models.CharField(max_length=300)),
                ('is_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.comment')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter2.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter2.user')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislikeComment',
            fields=[
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='twitter2.comment')),
                ('datetime', models.DateTimeField()),
                ('like_dislike', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], default='L', max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter2.user')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='twitter2.post')),
                ('datetime', models.DateTimeField()),
                ('like_dislike', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], default='L', max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter2.user')),
            ],
        ),
    ]
