# Generated by Django 4.1.2 on 2022-11-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user_id_follower', 'user_id_followed')},
        ),
    ]
