# Generated by Django 4.1.2 on 2023-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='likedislikecomment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
