# Generated by Django 4.1.2 on 2023-01-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter2', '0002_alter_likedislike_time_alter_likedislikecomment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='user_id_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='twitter2.post'),
        ),
        migrations.AlterField(
            model_name='likedislikecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='twitter2.comment'),
        ),
    ]
