# Generated by Django 4.1.2 on 2023-01-21 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter2', '0003_alter_following_user_id_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_id_followed',
            new_name='user_followed',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id_follower',
            new_name='user_follower',
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='likedislikecomment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user_follower', 'user_followed')},
        ),
    ]
