# Generated by Django 4.1.2 on 2023-01-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0003_alter_comment_is_reply_to_alter_post_is_reply_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
