# Generated by Django 4.1.2 on 2022-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0003_remove_comment_datetime_remove_following_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
