# Generated by Django 4.1.2 on 2022-11-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
