# Generated by Django 4.1.2 on 2023-01-21 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter2', '0004_rename_user_id_followed_following_user_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_follower',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'user_followed')},
        ),
    ]
