# Generated by Django 4.1.2 on 2023-01-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0006_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.post'),
        ),
    ]
