# Generated by Django 4.1.2 on 2023-01-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0007_alter_post_is_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply_to',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_reply_to',
        ),
    ]
