# Generated by Django 4.1.2 on 2023-01-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter2', '0009_alter_post_is_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter2.post'),
        ),
    ]
